// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqV-9aciLjOwThB5GUBMwq7TcXaimO6jI',
    appId: '1:1043316750333:web:4b65e96f6c5d9344bd4b94',
    messagingSenderId: '1043316750333',
    projectId: 'fir-6e787',
    authDomain: 'fir-6e787.firebaseapp.com',
    storageBucket: 'fir-6e787.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVlUJCH9bXePW3A_zlwE6Tq9B496uQHIc',
    appId: '1:1043316750333:android:69b77fa2d4f73575bd4b94',
    messagingSenderId: '1043316750333',
    projectId: 'fir-6e787',
    storageBucket: 'fir-6e787.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH5MuoXpSz8Vs9mQ0ztd4z7w_cjXm87ac',
    appId: '1:1043316750333:ios:cfcd4a9eaf563378bd4b94',
    messagingSenderId: '1043316750333',
    projectId: 'fir-6e787',
    storageBucket: 'fir-6e787.appspot.com',
    iosBundleId: 'com.example.flutterDevcampFirebaseSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH5MuoXpSz8Vs9mQ0ztd4z7w_cjXm87ac',
    appId: '1:1043316750333:ios:cfcd4a9eaf563378bd4b94',
    messagingSenderId: '1043316750333',
    projectId: 'fir-6e787',
    storageBucket: 'fir-6e787.appspot.com',
    iosBundleId: 'com.example.flutterDevcampFirebaseSignin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqV-9aciLjOwThB5GUBMwq7TcXaimO6jI',
    appId: '1:1043316750333:web:b2ca483c9721a367bd4b94',
    messagingSenderId: '1043316750333',
    projectId: 'fir-6e787',
    authDomain: 'fir-6e787.firebaseapp.com',
    storageBucket: 'fir-6e787.appspot.com',
  );
}
